name: Static Analysis

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']

jobs:
  analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install analysis tools
        run: sudo apt-get update && sudo apt-get install -y clang-tidy cppcheck

      - name: Run cppcheck
        run: cppcheck --enable=all --inconclusive --quiet --std=c99 --force . 2> cppcheck-report.txt

      - name: Run clang-tidy
        run: |
          find . -name '*.c' | while read file; do
            clang-tidy "$file" -- -std=c99 || true
          done
