name: C Build and Test for Chapter 1/Array
 
on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build program
      run: |
        mkdir -p bin
        gcc -o bin/allSymbols ChapterOne/Array/CounterAllSymbols.c

    - name: Run tests
      run: |
        bash ChapterOne/Array/Tests/allSymbols_test.sh

